version: '2'
services:
    mngtjob-app:
        image: mngtjob
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://mngtjob-postgresql:5432/mngtJob
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mngtjob-postgresql:
        extends:
            file: postgresql.yml
            service: mngtjob-postgresql
